django_playlist/djangonautic/articles/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path(r'', views.article_list, name='list'),
    path('<slug:slug>', views.article_detail, name='detail')
]

django_playlist/djangonautic/djangonautic/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

app_name = 'main'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('about/', views.about, name='about'),
    path('', views.home),
    path('user_auth/', include("django.contrib.auth.urls")),
    path('user_auth/', include("user_auth.urls")),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_playlist/djangonautic/user_auth/urls.py
from django.urls import path
from . import views

app_name = 'user_auth'
urlpatterns = [
    path('', views.user_login, name='login'),
    path('authenticate_user/', views.authenticate_user,
    name='authenticate_user'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_view, name='logout')
]

django_playlist/djangonautic/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title =  models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(null=True, blank=True)
    #add author

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:1500] + '...'

django_playlist/djangonautic/user_auth/models.py
from django.db import models

# Create your models here.

django_playlist/djangonautic/user_auth/forms.py
# Import all necessary functions
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Define a class that will create a form that will allow the user to register as a new user.
class UserRegistrationForm(UserCreationForm):
    """This method will define the user registration form as per the django template
        It adds more functionalities like first name, last name and email

        :param charfield first_name: The users first name
        :param Charfield last_name: The users last name
        :param Charfield email_address: The users email adress

        :returns: The sum of two numbers

        :rtype: int
    """
    first_name = forms.CharField(max_length=101)
    last_name = forms.CharField(max_length=101)
    email_address = forms.CharField()
    

    class Meta:
        model = User
        fields = ['username', 'last_name', 'first_name', 'email_address', 'password1', 'password2']

django_playlist/djangonautic/articles/views.py
from django.shortcuts import render, HttpResponse
from .models import Article

# Create your views here.
def article_list(request):
    articles = Article.objects.all().order_by('date')
    context = {'articles':articles}
    return render(request, 'articles/article_list.html', context)


def article_detail(request, slug):
    article = Article.objects.get(slug = slug)
    context = {'article':article}
    return render(request,'articles/article_detail.html',context )

django_playlist/djangonautic/djangonautic/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

def home(request):
    #return HttpResponse('home')
    return render(request, 'authentication/login.html')
    

def about(request):
    return render(request, 'about.html')

django_playlist/djangonautic/user_auth/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect
from django.http import HttpResponseRedirect
from .forms import UserRegistrationForm
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.forms import  AuthenticationForm

# Create your views here.
def user_login(request):
    return render(request, 'authentication/login.html')

def logout_view(request):
    return render(request, 'authentication/login.html')

def authenticate_user(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is None:
        return HttpResponseRedirect(
        reverse('user_auth:login')
        )
    else:
        login(request, user)
        return HttpResponseRedirect(
        reverse('articles:list')
        )
    
def authenticate_user(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is None:
        return HttpResponseRedirect(reverse('user_auth:user_login'))
    else:
        login(request, user)
        return HttpResponseRedirect(
            reverse('articles:list')
        )


# Define a function that will have a user register their account if they are a new user.
def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()

            messages.success(request, f'Your account has been created. You can log in now!')    
            return redirect('user_auth:login')
    else:
        form = UserRegistrationForm()

    context = {'form': form}
    return render(request, 'authentication/register.html', context)

django_playlist/djangonautic/articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<style>
    *img{
        width: 1000px;
    }
</style>
<div class="container">
    <div class="article-detail">
        <div class="article">
            <img src="{{ article.thumb.url }}" style="width: 1200px; height: 300px;">
            <h2> {{article.title}}</h2>
            <p>{{article.body}}</p>
            <p>{{article.date}}</p>
        </div>
    </div>
</div>

    
{% endblock %}

django_playlist/djangonautic/articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Article List</h1>
    <div class="container">
            {% for article in articles %}
            <div class="row">
                <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a></h2>
                <p>{{ article.snippet }}</p>
                <p>{{ article.date }}</p>
                <hr>
            </div>
            {% endfor %}
    </div>
{% endblock %}

django_playlist/djangonautic/templates/about.html
{% extends 'base_layout.html' %}

{% block content %}
        <h1>About us</h1>
        <div class="row">
            <div class="col-md-4">

            </div>
            <div class="col-md-4">
                <div class="container">
                    <p>A rudimentary blog website that served to purpose to test and showcase my skills.</p>
                </div>
            </div>
            <div class="col-md-4">
            
            </div>
        </div>
</html>
{% endblock %}

django_playlist/djangonautic/templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <style>
            #myhead {
                background-color: black;
                opacity: 0.6;
                font-weight: bolder;
                margin: 30px;
            }
            
            .container {
            background-color: rgba(0, 0, 0, 0.7); 
            border-radius: 10px;
            padding: 20px;
            margin-top: 20px;
            }
        </style>

        <meta charset="utf=8">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
        <title>Articles</title>
        <link rel="stylesheet" , href="{% static 'css/article_list.css' %}">
    </head>
    <body>
        <div class="container">
            <div class="row" id="myhead">
                <div class="col-md-1">
                    <h1><a href="{% url 'articles:list'%}" ><img src= "{% static 'images/djangonaut.jpg' %}" width="100"/></a></h1>
                </div>
                <div class="col-md-2">
                    <h1><a href="{% url 'articles:list' %}">Djangonaut</a></h1>
                </div>
                
                <div class="row">
                    <div class="col-md-9">

                    </div>
                    <div class="col-md-1">
                        <h6><a href="{% url 'articles:list' %}">Home</a></h6>
                    </div>
                    <div class="col-md-1">
                        <h6><a href="about">about us</a></h6>
                    </div>
                    <div class="col-md-1">
                        <h6><a href="{% url 'user_auth:login' %}">logout</a></h6>
                    </div>
                </div>
            </div>
            {% block content%}
            {% endblock %}
        </div>
    </body>
    <footer>
        <div class="container">
            <h6>created by: Luyanda Dlamini</h6>
        </div>
    </footer>
</html>

django_playlist/djangonautic/templates/home.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Home</title>
    </head>
    <body>
        <h1>Home page</h1>
        <p>Welcome djangonaut</p>
    </body>
</html>

django_playlist/djangonautic/user_auth/templates/authentication/login.html
{% extends 'base_layout.html' %}

{% block content %}
<h1> Login as User </h1>
<div class="row">
    <div class="col-md-4">

    </div>
    <div class="col-md-4">
        <div class="container">
            <form action="{% url 'user_auth:authenticate_user' %}" method="post">
                {% csrf_token %}
                <label>Username</label>
                <input type="text" name="username" placeholder="User" required>
                <br/><br/>
                <label>Password</label>
                <input type="password" name="password" required>
                <br/><br/>
                <input type="submit" value="Login" />
                <a href="{% url 'user_auth:register' %}">
                    <button type="button" type="button">register</button>
                </a>
            </form>
{% endblock %}

django_playlist/djangonautic/user_auth/templates/authentication/register.html
{% extends 'base_layout.html' %}

{% block content %}
<!--This is the user registration page-->
<h3>Register here</h3>
<hr>

<!--Create a predefined form from django that allows the user to register and submit their registration to the django database-->
<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Register</button>
</form>
{% endblock %}